### ISSUE TITLE
Problems reproducing the results

### ISSUE THREAD

**Issue by Cdfghglz** [LTTM/Scan-to-BIM#3]
Hi

I tried to reproduce the results according to the instructions.

1. Dataset inconsistency
I downloaded the dataset, then tried to match the folder structure defined in `data/HePIC/*.txt`. Some of the samples were missing which lead me to this diff:
```diff
diff --git a/data/HePIC/test.txt b/data/HePIC/test.txt
index cfb7a72..c92197a 100644
--- a/data/HePIC/test.txt
+++ b/data/HePIC/test.txt
@@ -4,16 +4,12 @@
 2_Castello/test/054.txt
 2_Castello/test/055.txt
 2_Castello/test/056.txt
-2_Castello/test/057.txt
 2_Castello/test/058.txt
 2_Castello/test/059.txt
 2_Castello/test/060.txt
 2_Castello/test/061.txt
-2_Castello/test/062.txt
-2_Castello/test/063.txt
 2_Castello/test/064.txt
 2_Castello/test/065.txt
-2_Castello/test/066.txt
 2_Castello/test/067.txt
 1_Eremitani/test/111.txt
 1_Eremitani/test/112.txt
diff --git a/data/HePIC/val.txt b/data/HePIC/val.txt
index 5e5cda0..3b5cc1f 100644
--- a/data/HePIC/val.txt
+++ b/data/HePIC/val.txt
@@ -4,16 +4,12 @@
 2_Castello/val/054.txt
 2_Castello/val/055.txt
 2_Castello/val/056.txt
-2_Castello/val/057.txt
 2_Castello/val/058.txt
 2_Castello/val/059.txt
 2_Castello/val/060.txt
 2_Castello/val/061.txt
-2_Castello/val/062.txt
-2_Castello/val/063.txt
 2_Castello/val/064.txt
 2_Castello/val/065.txt
-2_Castello/val/066.txt
 2_Castello/val/067.txt
 1_Eremitani/val/111.txt
 1_Eremitani/val/112.txt
```

2. Datapoints inconsistency
After matching the files, the data does not seem to hold the format defined in `PCSdataset.py`:
`  141:         # -16.385012495881597,29.048298990139457,237.51045999999994,Walls,051771850`
The training crashes on `/home/cdf/repos/Scan-to-BIM/hepic_split/1_Eremitani/val/112.txt` where the data looks like
`['-26.41259', '-5.663839000000002', '1.5128756', 'Walls']`

Can you please tell me if I am trying to reproduce in a correct way, and if so give some support.

Thanks

**Comment by elenacamuffo** [comment]
Hello

1. The 4 missing samples are deliberately missing, due to privacy constraints posed by the owner. However the result with those missing samples does not change much with respect to the original result. I removed them from the `val.txt` and `test.txt` lists.

2. I checked the data [here](https://drive.google.com/drive/folders/1NmRegFS9HQQx7IJ7Klpn8mgWbW6bv9Eo?usp=drive_link) and I confirm they hold the same format as described in `PCSdataset.py`.

If you have other issues, please let me know.

**Comment by Cdfghglz** [comment]
Hi, I updated the data from the link again and get this error:

```
/home/cdf/.miniconda3/envs/scan2bim/lib/python3.10/site-packages/torch/cuda/__init__.py:88: UserWarning: CUDA initialization: Unexpected error from cudaGetDeviceCount(). Did you run some cuda functions before calling NumCudaDevices() that might have already set an error? Error 804: forward compatibility was attempted on non supported HW (Triggered internally at /opt/conda/conda-bld/pytorch_1670525552843/work/c10/cuda/CUDAFunctions.cpp:109.)
  return torch._C._cuda_getDeviceCount() > 0
Validating Epoch 1:   0%|                                                        | 0/23 [00:00<?, ?it/s]/home/cdf/repos/Scan-to-BIM/hepic_split/2_Castello/val/051.txt
/home/cdf/repos/Scan-to-BIM/hepic_split/2_Castello/val/055.txt
Validating Epoch 1:   0%|                                                        | 0/23 [00:00<?, ?it/s]
/home/cdf/repos/Scan-to-BIM/hepic_split/2_Castello/val/060.txt
Traceback (most recent call last):
  File "/home/cdf/repos/Scan-to-BIM/train_pcs.py", line 138, in <module>
    miou, o, y = validate(writer, vset, vloader, e, model, device)
  File "/home/cdf/repos/Scan-to-BIM/train_pcs.py", line 30, in validate
    for x, y in tqdm(vloader, "Validating Epoch %d"%(epoch+1), total=len(vset)):
  File "/home/cdf/.miniconda3/envs/scan2bim/lib/python3.10/site-packages/tqdm/std.py", line 1181, in __iter__
    for obj in iterable:
  File "/home/cdf/.miniconda3/envs/scan2bim/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 628, in __next__
    data = self._next_data()
  File "/home/cdf/.miniconda3/envs/scan2bim/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 1333, in _next_data
    return self._process_data(data)
  File "/home/cdf/.miniconda3/envs/scan2bim/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 1359, in _process_data
    data.reraise()
  File "/home/cdf/.miniconda3/envs/scan2bim/lib/python3.10/site-packages/torch/_utils.py", line 543, in reraise
    raise exception
ValueError: Caught ValueError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/cdf/.miniconda3/envs/scan2bim/lib/python3.10/site-packages/torch/utils/data/_utils/worker.py", line 302, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/cdf/.miniconda3/envs/scan2bim/lib/python3.10/site-packages/torch/utils/data/_utils/fetch.py", line 58, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/cdf/.miniconda3/envs/scan2bim/lib/python3.10/site-packages/torch/utils/data/_utils/fetch.py", line 58, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/cdf/repos/Scan-to-BIM/dataloaders/PCSdataset.py", line 158, in __getitem__
    xyz, lab = zip(*[self.clean_line(l) for l in open(fname, 'r')])
  File "/home/cdf/repos/Scan-to-BIM/dataloaders/PCSdataset.py", line 158, in <listcomp>
    xyz, lab = zip(*[self.clean_line(l) for l in open(fname, 'r')])
  File "/home/cdf/repos/Scan-to-BIM/dataloaders/PCSdataset.py", line 142, in clean_line
    x, y, z, l, _ = l.strip().split(',')
ValueError: too many values to unpack (expected 5)
```

**Comment by elenacamuffo** [comment]
Yes, i found out there is an extra comma at the end of the line in some point cloud files.
I will take care of fixing that in the data. Meanwhile I updated the code in such a way the extra comma is ignored.
Now it should work properly.

**Comment by Cdfghglz** [comment]
Thanks, works
